development:
  adapter: postgresql
  database: daughters_development
  username: seandavis
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  username: seandavis
  database: daughters_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: daughters_production
  username: seandavis
  pool: 5
  timeout: 5000
