development:
  adapter: postgresql
  database: daughters_development
  password: passwd
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  username: srussell
  password: passwd
  database: daughters_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: daughters_production
  password: passwd
  pool: 5
  timeout: 5000
