common: &common
  adapter: postgresql
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: grezha_development

test:
  <<: *common
  database: grezha_test

production:
  <<: *common
  database: grezha_production

demo:
  <<: *common
  database: grezha_demo
